#!/bin/sh

INTERFACES_FILE="/boot/interfaces"
MATRIX_CMD="/boot/matrix_cmd.sh"

start() {
	echo "Setting up configuration"
	mkdir /boot
	mount -r /dev/mmcblk0p1 /boot
	if [ -e "$INTERFACES_FILE" ]; then
		echo "Copying network config"
		mkdir -p /etc/network
		cp $INTERFACES_FILE /etc/network/interfaces
	fi
	if [ -e "$MATRIX_CMD" ]; then
		echo "Copying rpi-matrix configuration"
		mkdir -p /root
		cp $TALLY_CMD /root/rpi-matrix/matrix_cmd.sh
		chmod a+x /root/tally_cmd.sh
	fi
}

stop() {
	true
}

restart() {
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
	;;
	restart|reload)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
