#!/bin/sh

start() {
	echo -"Starting rpi-matrix udp server"
	/root/rpi-matrix/matrix_cmd.sh
}

stop() {
	killall udp
}

restart() {
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
	;;
	restart|reload)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
